name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install foo-software Lighthouse
      run: npm install @foo-software/lighthouse-check

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Web Server in the background
      run: |
        cd src/WebApp
        dotnet run &

    - name: Create temporary folder for artifacts storage
      run: mkdir /tmp/lighthouse-artifacts

    # It runs the lighthouse report for a provided url and create a HTML report in the specified directory
    # Action documentation: https://github.com/marketplace/actions/lighthouse-check#usage-standard-example
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        prCommentEnabled: true
        outputDirectory: /tmp/artifacts # Used to upload artifacts.
        urls: 'https://localhost:7229'
        emulatedFormFactor: 'all' # Run LightHouse against "mobile", "desktop", or "all" devices
        overridesJsonFile: './lighthouse-config.json'
    
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts