
name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: dotnet build

    - name: Run Web Server in the background
      run: |
        cd src/WebApp
        dotnet run &

    - name: Create temporary folder for artifacts storage
      run: mkdir /tmp/lighthouse-artifacts

    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        outputDirectory: /tmp/lighthouse-artifacts
        urls: 'https://localhost:7229'
        emulatedFormFactor: 'all'
        overridesJsonFile: './lighthouse-config.json'

    # Using a pre-build action to make the action fail if your score is too low. It can be really interesting to track a low score on a commit
    # You can remove this action IF you don't want lighthouse to be a blocking point in your CI
    # This default values so you need to change them by your own criteria
    # Official documentation: https://github.com/foo-software/lighthouse-check-status-action
    - name: Handle Lighthouse Check results
      uses: ./
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "50"
        minBestPracticesScore: "50"
        minPerformanceScore: "95"
        minProgressiveWebAppScore: "50"
        minSeoScore: "50"

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/lighthouse-artifacts