name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install foo-software Lighthouse
      run: npm install @foo-software/lighthouse-check

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Web Server in the background
      run: |
        cd src/WebApp
        dotnet run &

    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        prCommentAccessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        prCommentUrl: "https://api.github.com/repos/gaepdit/template-app/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews"
        outputDirectory: /tmp/artifacts
        urls: 'https://localhost:7229'
        emulatedFormFactor: 'all'
        overridesJsonFile: './lighthouse-config.json'
    
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts