
name: Lighthouse Check
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up Node.js (npm)
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: dotnet build

    - name: Run Web Server in the background
      run: |
        cd src/WebApp
        dotnet run &

    - name: Installing Lighthouse through NPM
      run: |
        cd .github/workflows/.lighthouse
        npm install
      
    - name: Run Lighthouse Check
      run: |
        node ./dist/bin/lighthouse-check.js \
        --verbose \
        --prCommentEnabled \
        --emulatedFormFactor "all" \
        --urls "https://localhost:7229" \
        --prCommentAccessToken "${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}" \
        --prCommentUrl "https://api.github.com/repos/gaepdit/template-app/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews"
